name: Schedule Run Sendxyh

on:
  push:
    branches:
      - main
  schedule:
    # 美东时间UTC/GMT -4: - cron: '30 21 * * 1-5'
    - cron: '30 1 * * 2-6'

jobs:
  build_run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Download Stooq Data
        run: |
          wget -q https://static.stooq.com/db/h/d_us_txt.zip
          unzip -oq d_us_txt.zip
      
      - name: sendxyh
        run: python3 sendxyh.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          XYHCHAT: ${{ secrets.XYHCHAT }}
          XYHLOG: ${{ secrets.XYHLOG }}
          XYHTICKER: "[['SPY',10,50,100,200],['QQQ',13,55,100,150,200],['IWM',13,55,100,150,200]]"
          XYHSOURCE: stooq

          